<a href="https://colab.research.google.com/github/akshaykumar2972/Banking-Data-Analysis/blob/main/Banking_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [252]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [253]:
df = pd.read_csv('/content/logistic_regression.csv').drop_duplicates()
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,...,16.0,0.0,36369.0,41.8,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,...,17.0,0.0,20131.0,53.3,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,...,13.0,0.0,11987.0,92.2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,...,6.0,0.0,5472.0,21.5,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,...,13.0,0.0,24584.0,69.8,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

In [254]:
df.shape

(396030, 27)

In [255]:
df.iloc[:,:11].head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,Not Verified
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,Not Verified
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,Source Verified
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,Not Verified
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,Verified

In [256]:
df['loan_amnt'] = df['loan_amnt'].astype(int)

In [257]:
df['term'] = df['term'].apply(lambda x: int(x.split()[0]))

In [258]:
df['emp_length'] = df['emp_length'].replace({'< 1 year': '0.5 years', '10+ years': '12 years'})

In [259]:
df['emp_length'].value_counts()

emp_length
12 years     126041
2 years       35827
0.5 years     31725
3 years       31665
5 years       26495
1 year        25882
4 years       23952
6 years       20841
7 years       20819
8 years       19168
9 years       15314
Name: count, dtype: int64

In [260]:
df['emp_length'] = pd.to_numeric(df['emp_length'].str.extract(r'(\d+\.?\d*)')[0])

In [261]:
df.iloc[:,:11].head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status
0,10000,36,11.44,329.48,B,B4,Marketing,12.0,RENT,117000.0,Not Verified
1,8000,36,11.99,265.68,B,B5,Credit analyst,4.0,MORTGAGE,65000.0,Not Verified
2,15600,36,10.49,506.97,B,B3,Statistician,0.5,RENT,43057.0,Source Verified
3,7200,36,6.49,220.65,A,A2,Client Advocate,6.0,RENT,54000.0,Not Verified
4,24375,60,17.27,609.33,C,C5,Destiny Management Inc.,9.0,MORTGAGE,55000.0,Verified

In [262]:
df.rename(columns={'loan_amnt':'loan_amount_requested'
                  ,'int_rate':'interest_rate'
                  ,'grade':'assigned_loan_grade'
                  ,'sub_grade':'assigned_loan_subgrade'
                  ,'emp_title':'occupation'
                  ,'emp_length':'years_of_experience'
                  ,'annual_inc':'annual_income'}, inplace=True)

In [263]:
df.iloc[:,11:20].head()

,issue_d,loan_status,purpose,title,dti,earliest_cr_line,open_acc,pub_rec,revol_bal
0,Jan-2015,Fully Paid,vacation,Vacation,26.24,Jun-1990,16.0,0.0,36369.0
1,Jan-2015,Fully Paid,debt_consolidation,Debt consolidation,22.05,Jul-2004,17.0,0.0,20131.0
2,Jan-2015,Fully Paid,credit_card,Credit card refinancing,12.79,Aug-2007,13.0,0.0,11987.0
3,Nov-2014,Fully Paid,credit_card,Credit card refinancing,2.60,Sep-2006,6.0,0.0,5472.0
4,Apr-2013,Charged Off,credit_card,Credit Card Refinance,33.95,Mar-1999,13.0,0.0,24584.0

In [264]:
df.rename(columns={'issue_d':'issued_month'
                  ,'open_acc':'open_credit_lines'
                  ,'dti':'debt_to_income_ratio'
                  ,'pub_rec':'derogatory_public_records'
                  ,'revol_bal':'revolving_credit_balance'}, inplace=True)

In [265]:
df['purpose'].value_counts().reset_index()

               purpose   count
0   debt_consolidation  234507
1          credit_card   83019
2     home_improvement   24030
3                other   21185
4       major_purchase    8790
5       small_business    5701
6                  car    4697
7              medical    4196
8               moving    2854
9             vacation    2452
10               house    2201
11             wedding    1812
12    renewable_energy     329
13         educational     257

In [266]:
loan_title = df['title'].value_counts().reset_index()
loan_title[loan_title['count'] > 100]['title'].unique()

array(['Debt consolidation', 'Credit card refinancing',
       'Home improvement', 'Other', 'Debt Consolidation',
       'Major purchase', 'Consolidation', 'debt consolidation',
       'Business', 'Debt Consolidation Loan', 'Medical expenses',
       'Car financing', 'Credit Card Consolidation', 'Vacation',
       'Moving and relocation', 'consolidation', 'Personal Loan',
       'Consolidation Loan', 'Home Improvement', 'Home buying',
       'Credit Card Refinance', 'Credit Card Payoff', 'Consolidate',
       'Personal', 'Loan', 'Credit Card Loan', 'Freedom', 'consolidate',
       'personal', 'personal loan', 'Debt', 'home improvement', 'Payoff',
       'Credit Cards', 'payoff', 'Credit Card', 'DEBT CONSOLIDATION',
       'Home Improvement Loan', 'Debt Consolidation ',
       'credit card payoff', 'My Loan', 'Small Business Loan',
       'credit card consolidation', 'credit card refinance', 'Debt Free',
       'Refinance', 'Wedding', 'Wedding Loan', 'loan', 'debt',
       'CC Consolidation', 'Debt Loan', 'Credit Consolidation',
       'Credit card consolidation', 'credit cards', 'consolidation loan',
       'freedom', 'debt consolidation loan', 'credit card', 'Car Loan',
       'Credit Card Refi', 'Credit card payoff', 'Debt Payoff',
       'Personal loan', 'debt_consolidation', 'Debt consolidation loan',
       'Medical', 'Credit Card Debt Consolidation',
       'Credit card refinance', 'my loan', 'Debt consolidation ',
       'Consolidation loan', 'Credit Card Refinancing',
       'Bill Consolidation', 'Home', 'debt free', 'Lending Club',
       'Loan 1', 'Credit Card Debt', 'pay off credit cards',
       'Consolidation ', 'My loan', 'Credit cards', 'Bills', 'CC Payoff',
       'Lending Club Loan', 'Green loan', 'Loan Consolidation',
       'Pay off credit cards', 'pay off', 'Other Loan', 'Business Loan',
       'Major Purchase', 'Credit Card Pay Off', 'debt loan',
       'debt consolidation ', 'Major Purchase Loan', 'Pool', 'Pay Off',
       'Home Improvements', 'CC Loan', 'CC Refinance', 'Debt Consol',
       'Fresh Start', 'Credit Card Consolidation Loan', 'bills',
       'refinance', 'vacation', 'Wedding expenses', 'credit card pay off',
       'Debt Consolodation', 'CONSOLIDATION', 'Debt payoff', 'Debt free',
       'Moving Loan', 'credit card loan', 'Pool Loan', 'Medical Loan',
       'CC Refi', 'Pay off', 'debt payoff', 'Loan1', 'Freedom Loan',
       'Debt Reduction', 'home', 'wedding', 'Credit Card Refinance Loan',
       'Relief', 'credit card debt', 'Wedding Expenses', 'Moving',
       'Consolidate Debt', 'Debit Consolidation', 'Refi', 'Debt loan',
       'Debt Relief', 'Credit card', 'Credit'], dtype=object)

In [267]:
df.iloc[:,21:].head()

,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

In [268]:
df['application_type'].value_counts()

application_type
INDIVIDUAL    395319
JOINT            425
DIRECT_PAY       286
Name: count, dtype: int64

In [269]:
df.rename(columns={'mort_acc':'mortgage_accounts', 'pub_rec_bankruptcies':'public_record_bankruptcies'}, inplace=True)

In [270]:
df['public_record_bankruptcies'].value_counts()

public_record_bankruptcies
0.0    350380
1.0     42790
2.0      1847
3.0       351
4.0        82
5.0        32
6.0         7
7.0         4
8.0         2
Name: count, dtype: int64

In [271]:
pd.set_option('display.max_colwidth', None)
df['address'].sample(25)

346499         64310 Bray Junctions Suite 675\r\nEast Sandra, UT 48052
330167             4643 Janice Forge Apt. 563\r\nNorth Wayne, NH 70466
288564            8289 Davis Junction Suite 819\r\nRandyland, WY 48052
59761                      641 Jeremy Brooks\r\nRobbinsburgh, RI 30723
35948                      01769 Kimberly Circle\r\nAlanport, ND 70466
194556                      595 Autumn Circle\r\nKristenstad, FL 30723
214856                    05449 Denise Corners\r\nAndreville, NE 48052
254360                634 Fernando Loaf Apt. 486\r\nJanestad, AZ 70466
85679                      4044 Patrick Greens\r\nMartintown, PA 30723
264896                       5707 Rojas Curve\r\nSouth James, MA 00813
264360                      364 Gary Mission\r\nWest Brandon, CO 93700
162250                  4559 Kevin Plaza\r\nNew Isaacborough, IA 70466
139422                     569 Pittman Courts\r\nNorth Patty, SD 48052
62440     752 White Garden Suite 105\r\nWest Patriciachester, MS 93700
57930                 8488 Larry Bridge\r\nPort Michaelmouth, VT 22690
59496               50273 Wilson Plains\r\nLake Dianechester, MT 00813
251734            32911 Jordan Ports Suite 039\r\nNew Amanda, MA 48052
340679                              PSC 5571, Box 5355\r\nAPO AP 48052
136263         133 Bailey Vista Suite 832\r\nNorth Sarahtown, MS 29597
252684      46115 Marissa Center Suite 475\r\nWest Tylerfort, OK 30723
226574                           356 Kim Plains\r\nNorth Amy, WY 22690
64982         9923 Morris Lodge Suite 037\r\nNew Gregoryview, AR 22690
74435           38120 Felicia Mall Apt. 822\r\nAshleyborough, NM 22690
393631             2621 Gina Tunnel Apt. 096\r\nWilliamsstad, SC 48052
27678                     07923 Harris Tunnel\r\nJessicaberg, HI 22690
Name: address, dtype: object

In [272]:
temp_split = df['address'].str.split('\n').str[1].str.split(',', expand=True)

df['city'] = temp_split[0].str.strip()
df['state'] = temp_split[1].str.strip().str.split(' ').str[0]
df['zip_code'] = temp_split[1].str.strip().str.split(' ').str[1]

In [273]:
df[['address','city','state','zip_code']].sample(25)

,address,city,state,zip_code
159044,"220 Sanders Island Suite 775\r\nJenniferport, CO 30723",Jenniferport,CO,30723
164384,"106 Clark Islands\r\nLake Joyceburgh, MS 30723",Lake Joyceburgh,MS,30723
234025,"149 Johnson Mission\r\nHernandezport, RI 48052",Hernandezport,RI,48052
197811,"1681 Tanner Extension Apt. 408\r\nSouth David, DC 22690",South David,DC,22690
166793,"062 Estrada Wells Suite 658\r\nEast Patricia, VA 48052",East Patricia,VA,48052
62701,"0442 Brittany Islands\r\nEast Michaeltown, MO 70466",East Michaeltown,MO,70466
105604,"08188 Susan Ways Suite 787\r\nMatthewberg, NJ 70466",Matthewberg,NJ,70466
298498,"987 Gregory Squares Apt. 123\r\nLake Christopherhaven, LA 29597",Lake Christopherhaven,LA,29597
214802,"1307 Adam Knoll Apt. 300\r\nLake John, MT 29597",Lake John,MT,29597
269191,"428 Swanson Lights Apt. 777\r\nBrandonside, CT 70466",Brandonside,CT,70466
138364,"650 Flynn Loop\r\nEast Kariport, WY 05113",East Kariport,WY,05113
61249,"810 Justin Row\r\nSweeneyton, WI 05113",Sweeneyton,WI,05113
212587,USS Harris\r\nFPO AE 29597,FPO AE 29597,None,None
139539,"5598 Jennifer Shores Suite 699\r\nPort Alexbury, WA 48052",Port Alexbury,WA,48052
48789,"5442 Larsen Divide\r\nCraigchester, MD 86630",Craigchester,MD,86630
262280,"00889 Terri Creek Suite 242\r\nNorth Jill, MT 29597",North Jill,MT,29597
134359,USCGC Aguirre\r\nFPO AP 30723,FPO AP 30723,None,None
328639,"15996 Davis Fall\r\nPetersfurt, GA 05113",Petersfurt,GA,05113
188679,"393 Amy Ports\r\nNorth Justin, MI 05113",North Justin,MI,05113
146840,USS Franklin\r\nFPO AP 22690,FPO AP 22690,None,None
338320,"44298 Kelly Hill\r\nOlsenfort, MD 30723",Olsenfort,MD,30723
15242,"160 Davis Locks Suite 706\r\nNorth Courtneyberg, AK 48052",North Courtneyberg,AK,48052
156883,"3869 Lisa Mission\r\nSouth Ericmouth, CA 30723",South Ericmouth,CA,30723
150729,"4988 Jesus Junctions Apt. 836\r\nHornmouth, SC 00813",Hornmouth,SC,00813
112429,"914 Henry Brook Apt. 594\r\nLake Davidbury, PA 00813",Lake Davidbury,PA,00813

In [274]:
df[df.index == 180525]

,loan_amount_requested,term,interest_rate,installment,assigned_loan_grade,assigned_loan_subgrade,occupation,years_of_experience,home_ownership,annual_income,...,revol_util,total_acc,initial_list_status,application_type,mortgage_accounts,public_record_bankruptcies,address,city,state,zip_code
180525,24000,36,6.03,730.46,A,A1,"VP, Senior Analyst",8.0,MORTGAGE,150000.0,...,41.8,19.0,w,INDIVIDUAL,2.0,0.0,Unit 3246 Box 6049\r\nDPO AE 00813,DPO AE 00813,None,None

In [275]:
df[df['state'].isna()]['city'].unique()

array(['FPO AE 30723', 'FPO AP 22690', 'DPO AE 05113', 'DPO AE 48052',
       'FPO AA 30723', 'APO AP 05113', 'APO AA 22690', 'FPO AE 22690',
       'FPO AA 48052', 'DPO AE 29597', 'FPO AP 29597', 'FPO AE 05113',
       'FPO AP 30723', 'DPO AE 86630', 'APO AP 29597', 'DPO AP 30723',
       'FPO AP 00813', 'FPO AA 11650', 'APO AP 11650', 'APO AA 48052',
       'APO AE 48052', 'DPO AA 29597', 'DPO AP 48052', 'FPO AE 00813',
       'DPO AA 30723', 'APO AA 30723', 'FPO AA 29597', 'APO AA 70466',
       'APO AE 29597', 'DPO AA 22690', 'APO AE 00813', 'FPO AA 70466',
       'DPO AE 93700', 'APO AE 05113', 'FPO AE 48052', 'DPO AP 00813',
       'APO AA 11650', 'APO AE 11650', 'APO AP 22690', 'APO AE 30723',
       'FPO AE 70466', 'DPO AP 29597', 'APO AE 70466', 'FPO AA 22690',
       'FPO AE 29597', 'DPO AE 30723', 'DPO AP 70466', 'FPO AA 05113',
       'DPO AE 22690', 'APO AE 22690', 'DPO AE 00813', 'APO AP 00813',
       'DPO AA 48052', 'DPO AE 70466', 'APO AA 00813', 'APO AA 86630',
       'APO AA 29597', 'APO AA 05113', 'DPO AP 86630', 'DPO AP 93700',
       'APO AP 70466', 'FPO AP 48052', 'FPO AP 70466', 'DPO AA 00813',
       'FPO AA 00813', 'DPO AP 11650', 'DPO AP 22690', 'FPO AP 05113',
       'FPO AA 86630', 'DPO AE 11650', 'APO AP 48052', 'APO AP 30723',
       'FPO AP 86630', 'DPO AA 70466', 'APO AP 93700', 'DPO AA 05113',
       'DPO AA 86630', 'APO AA 93700', 'APO AE 93700', 'DPO AP 05113',
       'APO AP 86630', 'APO AE 86630', 'FPO AP 11650', 'FPO AP 93700',
       'DPO AA 93700', 'DPO AA 11650', 'FPO AE 86630', 'FPO AA 93700',
       'FPO AE 11650', 'FPO AE 93700'], dtype=object)

In [276]:
missing_state = df[df['state'].isna()]
extracted = missing_state['city'].str.extract(r'(?P<c>APO|FPO|DPO)\s+(?P<s>[A-Z]{2})\s+(?P<z>\d{5})')
extracted

          c   s      z
7       FPO  AE  30723
8       FPO  AP  22690
19      DPO  AE  05113
26      DPO  AE  48052
33      FPO  AA  30723
...     ...  ..    ...
395995  APO  AP  22690
395997  APO  AP  22690
396010  APO  AA  05113
396012  DPO  AP  29597
396015  DPO  AA  05113

[42384 rows x 3 columns]

In [277]:
df.loc[missing_state.index, 'city'] = extracted['c']
df.loc[missing_state.index, 'state'] = extracted['s']
df.loc[missing_state.index, 'zip_code'] = extracted['z']

In [278]:
df['city'] = df['city'].str.strip()
df['state'] = df['state'].str.strip()

In [279]:
df['zip_code'].unique()

array(['22690', '05113', '00813', '11650', '30723', '70466', '29597',
       '48052', '86630', '93700'], dtype=object)

In [280]:
df[df['state'].isna()]

Empty DataFrame
Columns: [loan_amount_requested, term, interest_rate, installment, assigned_loan_grade, assigned_loan_subgrade, occupation, years_of_experience, home_ownership, annual_income, verification_status, issued_month, loan_status, purpose, title, debt_to_income_ratio, earliest_cr_line, open_credit_lines, derogatory_public_records, revolving_credit_balance, revol_util, total_acc, initial_list_status, application_type, mortgage_accounts, public_record_bankruptcies, address, city, state, zip_code]
Index: []

[0 rows x 30 columns]

In [281]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 30 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amount_requested       396030 non-null  int64
 1   term                        396030 non-null  int64
 2   interest_rate               396030 non-null  float64
 3   installment                 396030 non-null  float64
 4   assigned_loan_grade         396030 non-null  object
 5   assigned_loan_subgrade      396030 non-null  object
 6   occupation                  373103 non-null  object
 7   years_of_experience         377729 non-null  float64
 8   home_ownership              396030 non-null  object
 9   annual_income               396030 non-null  float64
 10  verification_status         396030 non-null  object
 11  issued_month                396030 non-null  object
 12  loan_status                 396030 non-null  object
 13  purpose                     396030 non-null  object
 14  title                       394274 non-null  object
 15  debt_to_income_ratio        396030 non-null  float64
 16  earliest_cr_line            396030 non-null  object
 17  open_credit_lines           396030 non-null  float64
 18  derogatory_public_records   396030 non-null  float64
 19  revolving_credit_balance    396030 non-null  float64
 20  revol_util                  395754 non-null  float64
 21  total_acc                   396030 non-null  float64
 22  initial_list_status         396030 non-null  object
 23  application_type            396030 non-null  object
 24  mortgage_accounts           358235 non-null  float64
 25  public_record_bankruptcies  395495 non-null  float64
 26  address                     396030 non-null  object
 27  city                        396030 non-null  object
 28  state                       396030 non-null  object
 29  zip_code                    396030 non-null  object
dtypes: float64(12), int64(2), object(16)
memory usage: 90.6+ MB

In [282]:
df.describe()

,loan_amount_requested,term,interest_rate,installment,years_of_experience,annual_income,debt_to_income_ratio,open_credit_lines,derogatory_public_records,revolving_credit_balance,revol_util,total_acc,mortgage_accounts,public_record_bankruptcies
count,396030.000000,396030.000000,396030.000000,396030.000000,377729.000000,3.960300e+05,396030.000000,396030.000000,396030.000000,3.960300e+05,395754.000000,396030.000000,358235.000000,395495.000000
mean,14113.888089,41.698053,13.639400,431.849698,6.647934,7.420318e+04,17.379514,11.311153,0.178191,1.584454e+04,53.791749,25.414744,1.813991,0.121648
std,8357.441341,10.212038,4.472157,250.727790,4.366374,6.163762e+04,18.019092,5.137649,0.530671,2.059184e+04,24.452193,11.886991,2.147930,0.356174
min,500.000000,36.000000,5.320000,16.080000,0.500000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,2.000000,0.000000,0.000000
25%,8000.000000,36.000000,10.490000,250.330000,3.000000,4.500000e+04,11.280000,8.000000,0.000000,6.025000e+03,35.800000,17.000000,0.000000,0.000000
50%,12000.000000,36.000000,13.330000,375.430000,6.000000,6.400000e+04,16.910000,10.000000,0.000000,1.118100e+04,54.800000,24.000000,1.000000,0.000000
75%,20000.000000,36.000000,16.490000,567.300000,12.000000,9.000000e+04,22.980000,14.000000,0.000000,1.962000e+04,72.900000,32.000000,3.000000,0.000000
max,40000.000000,60.000000,30.990000,1533.810000,12.000000,8.706582e+06,9999.000000,90.000000,86.000000,1.743266e+06,892.300000,151.000000,34.000000,8.000000

In [283]:
df.describe(include='object')

,assigned_loan_grade,assigned_loan_subgrade,occupation,home_ownership,verification_status,issued_month,loan_status,purpose,title,earliest_cr_line,initial_list_status,application_type,address,city,state,zip_code
count,396030,396030,373103,396030,396030,396030,396030,396030,394274,396030,396030,396030,396030,396030,396030,396030
unique,7,35,173105,6,3,115,2,14,48816,684,2,3,393700,67513,54,10
top,B,B3,Teacher,MORTGAGE,Verified,Oct-2014,Fully Paid,debt_consolidation,Debt consolidation,Oct-2000,f,INDIVIDUAL,USS Johnson\r\nFPO AE 48052,DPO,AP,70466
freq,116018,26655,4389,198348,139563,14846,318357,234507,152472,3017,238066,395319,8,14289,14308,56985

In [284]:
df.isnull().sum()

loan_amount_requested             0
term                              0
interest_rate                     0
installment                       0
assigned_loan_grade               0
assigned_loan_subgrade            0
occupation                    22927
years_of_experience           18301
home_ownership                    0
annual_income                     0
verification_status               0
issued_month                      0
loan_status                       0
purpose                           0
title                          1756
debt_to_income_ratio              0
earliest_cr_line                  0
open_credit_lines                 0
derogatory_public_records         0
revolving_credit_balance          0
revol_util                      276
total_acc                         0
initial_list_status               0
application_type                  0
mortgage_accounts             37795
public_record_bankruptcies      535
address                           0
city                              0
state                             0
zip_code                          0
dtype: int64

In [285]:
df['occupation'].fillna('Unspecified', inplace=True)

/tmp/ipykernel_1520/933367638.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['occupation'].fillna('Unspecified', inplace=True)

In [286]:
df[df['occupation'].isna()]

Empty DataFrame
Columns: [loan_amount_requested, term, interest_rate, installment, assigned_loan_grade, assigned_loan_subgrade, occupation, years_of_experience, home_ownership, annual_income, verification_status, issued_month, loan_status, purpose, title, debt_to_income_ratio, earliest_cr_line, open_credit_lines, derogatory_public_records, revolving_credit_balance, revol_util, total_acc, initial_list_status, application_type, mortgage_accounts, public_record_bankruptcies, address, city, state, zip_code]
Index: []

[0 rows x 30 columns]

In [287]:
median_val = df['years_of_experience'].median()
df['years_of_experience'] = df['years_of_experience'].fillna(median_val)

In [288]:
df[df['years_of_experience'].isna()]

Empty DataFrame
Columns: [loan_amount_requested, term, interest_rate, installment, assigned_loan_grade, assigned_loan_subgrade, occupation, years_of_experience, home_ownership, annual_income, verification_status, issued_month, loan_status, purpose, title, debt_to_income_ratio, earliest_cr_line, open_credit_lines, derogatory_public_records, revolving_credit_balance, revol_util, total_acc, initial_list_status, application_type, mortgage_accounts, public_record_bankruptcies, address, city, state, zip_code]
Index: []

[0 rows x 30 columns]

In [289]:
df.iloc[:,11:20][df['title'].isna()].sample(25)

,issued_month,loan_status,purpose,title,debt_to_income_ratio,earliest_cr_line,open_credit_lines,derogatory_public_records,revolving_credit_balance
134343,Jan-2016,Charged Off,medical,NaN,0.79,Jul-1977,11.0,0.0,4404.0
82388,Apr-2016,Fully Paid,home_improvement,NaN,20.24,Sep-2009,24.0,1.0,15700.0
122236,Jan-2016,Fully Paid,debt_consolidation,NaN,24.32,Feb-1979,29.0,0.0,19768.0
293523,Apr-2016,Fully Paid,debt_consolidation,NaN,19.03,Jan-1959,8.0,0.0,22385.0
302967,Jan-2016,Fully Paid,debt_consolidation,NaN,4.39,Oct-2001,10.0,1.0,6120.0
352670,Feb-2016,Fully Paid,credit_card,NaN,19.70,Nov-2000,29.0,0.0,90385.0
198091,Mar-2016,Charged Off,small_business,NaN,17.40,Nov-1999,16.0,1.0,20061.0
82691,Jan-2016,Fully Paid,debt_consolidation,NaN,11.11,Jul-2005,5.0,0.0,6571.0
264721,Mar-2016,Fully Paid,debt_consolidation,NaN,8.93,Jun-2008,4.0,0.0,13024.0
352809,Feb-2016,Fully Paid,debt_consolidation,NaN,6.42,Nov-1990,8.0,0.0,13490.0
190564,Mar-2016,Fully Paid,debt_consolidation,NaN,21.39,Jun-2005,14.0,0.0,6049.0
103250,Jan-2016,Fully Paid,debt_consolidation,NaN,37.11,Dec-2001,10.0,1.0,11786.0
109204,Mar-2016,Charged Off,debt_consolidation,NaN,16.32,Jan-2008,9.0,0.0,7041.0
96990,Jan-2016,Fully Paid,major_purchase,NaN,3.46,Sep-2004,6.0,0.0,4748.0
243808,Jan-2016,Charged Off,debt_consolidation,NaN,16.29,Apr-2002,16.0,0.0,13821.0
96630,Feb-2016,Fully Paid,debt_consolidation,NaN,33.09,Oct-2006,8.0,1.0,4506.0
32602,Feb-2016,Fully Paid,other,NaN,13.35,Mar-2008,4.0,0.0,3372.0
305386,Jan-2016,Charged Off,debt_consolidation,NaN,21.19,Aug-1998,6.0,0.0,2611.0
366668,Mar-2016,Fully Paid,credit_card,NaN,19.34,May-2007,10.0,0.0,10936.0
144641,Feb-2016,Fully Paid,credit_card,NaN,11.30,Nov-1996,10.0,0.0,23211.0
191959,Mar-2016,Charged Off,debt_consolidation,NaN,24.16,May-2006,11.0,0.0,2953.0
175095,Feb-2016,Fully Paid,debt_consolidation,NaN,16.11,Sep-1994,15.0,0.0,11959.0
44112,Mar-2016,Fully Paid,other,NaN,14.26,Nov-1994,13.0,0.0,4973.0
87707,Mar-2016,Fully Paid,credit_card,NaN,8.88,Dec-1970,7.0,0.0,3880.0
251690,Apr-2016,Charged Off,debt_consolidation,NaN,45.35,Mar-2006,18.0,1.0,8940.0

In [290]:
df[df['title'].isna()]['purpose'].unique()

array(['debt_consolidation', 'credit_card', 'other', 'small_business',
       'home_improvement', 'medical', 'major_purchase', 'house', 'moving',
       'vacation', 'car', 'educational', 'renewable_energy'], dtype=object)

In [291]:
df['title'].fillna('Loan_reason_not_specified', inplace=True)

/tmp/ipykernel_1520/2530785282.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['title'].fillna('Loan_reason_not_specified', inplace=True)

In [292]:
df[df['revol_util'].isna()][['total_acc', 'open_credit_lines', 'revolving_credit_balance', 'revol_util']].sample(25)

        total_acc  open_credit_lines  revolving_credit_balance  revol_util
186790       49.0                5.0                       0.0         NaN
290425       11.0                2.0                       0.0         NaN
230584        5.0                2.0                       0.0         NaN
62170        12.0                2.0                       0.0         NaN
69710        18.0                4.0                       0.0         NaN
95326        16.0                5.0                       0.0         NaN
286608       17.0                3.0                       0.0         NaN
160248        5.0                0.0                       0.0         NaN
140675       27.0                9.0                       0.0         NaN
166771       14.0                5.0                       0.0         NaN
214643       32.0                8.0                       0.0         NaN
23353        11.0                5.0                       0.0         NaN
343379        8.0                2.0                       0.0         NaN
1686         21.0                2.0                       0.0         NaN
218140       29.0                7.0                  177665.0         NaN
58026        11.0                5.0                       0.0         NaN
171140       22.0                6.0                       0.0         NaN
127579       56.0                9.0                    5330.0         NaN
237564       36.0               11.0                       0.0         NaN
296609       29.0                2.0                       0.0         NaN
58465        13.0                3.0                       0.0         NaN
320148       12.0                2.0                       0.0         NaN
218079       18.0                6.0                   56071.0         NaN
183661       31.0                3.0                       0.0         NaN
240417        8.0                1.0                       0.0         NaN

In [293]:
# Updated query using your actual column names
# We'll check revolving_credit_balance and open_credit_lines to investigate the NaNs
df[df['revol_util'].isna()][['revolving_credit_balance', 'revol_util', 'open_credit_lines', 'total_acc']].sample(25)

        revolving_credit_balance  revol_util  open_credit_lines  total_acc
342749                   91109.0         NaN                8.0       26.0
156841                       0.0         NaN                2.0        4.0
199456                       0.0         NaN                5.0       22.0
290298                   16939.0         NaN                7.0       21.0
19496                    86913.0         NaN                4.0       21.0
146706                   40156.0         NaN                3.0       10.0
143741                    2964.0         NaN                8.0       23.0
290425                       0.0         NaN                2.0       11.0
239931                       0.0         NaN                5.0       12.0
158916                       0.0         NaN                3.0       26.0
374472                       0.0         NaN                3.0       35.0
88810                        0.0         NaN                7.0       30.0
89810                        0.0         NaN                3.0       22.0
107184                       0.0         NaN                0.0       19.0
290973                       0.0         NaN               10.0       37.0
58173                    15304.0         NaN                9.0       27.0
121172                       0.0         NaN                3.0       15.0
223775                       0.0         NaN                9.0       36.0
170135                       0.0         NaN                4.0       14.0
207406                       0.0         NaN                9.0       32.0
73696                        0.0         NaN                5.0       24.0
26697                        0.0         NaN                2.0       44.0
54020                        0.0         NaN                4.0       18.0
341221                  146843.0         NaN                6.0       26.0
85293                        0.0         NaN                3.0       18.0

In [294]:
# 1. Calculate the median for revol_util
revol_median = df['revol_util'].median()

# 2. Case A: Balance is 0 -> Utilization is 0
# We target rows where revol_util is NaN AND balance is 0
zero_bal_mask = (df['revol_util'].isna()) & (df['revolving_credit_balance'] == 0)
df.loc[zero_bal_mask, 'revol_util'] = 0

# 3. Case B: Balance > 0 but util is NaN (like row 33284) -> Fill with Median
# This handles the remaining NaNs in one go
df['revol_util'] = df['revol_util'].fillna(revol_median)

# 4. Final Cleanup: Remove those \r\n characters from the address column
# This will make your first image's output look much cleaner
df['address'] = df['address'].str.replace(r'\r\n', ' ', regex=True)

In [295]:
# Verify no nulls remain in revol_util
print(f"Remaining nulls in revol_util: {df['revol_util'].isna().sum()}")

# Check that high balance row specifically
print(df.loc[[33284], ['revolving_credit_balance', 'revol_util']])

Remaining nulls in revol_util: 0
       revolving_credit_balance  revol_util
33284                   41345.0        54.8

In [296]:
df.isnull().sum()

loan_amount_requested             0
term                              0
interest_rate                     0
installment                       0
assigned_loan_grade               0
assigned_loan_subgrade            0
occupation                        0
years_of_experience               0
home_ownership                    0
annual_income                     0
verification_status               0
issued_month                      0
loan_status                       0
purpose                           0
title                             0
debt_to_income_ratio              0
earliest_cr_line                  0
open_credit_lines                 0
derogatory_public_records         0
revolving_credit_balance          0
revol_util                        0
total_acc                         0
initial_list_status               0
application_type                  0
mortgage_accounts             37795
public_record_bankruptcies      535
address                           0
city                              0
state                             0
zip_code                          0
dtype: int64

In [297]:
df['mortgage_accounts'].fillna(0, inplace=True)
df['public_record_bankruptcies'].fillna(0, inplace=True)

/tmp/ipykernel_1520/1402155349.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mortgage_accounts'].fillna(0, inplace=True)
/tmp/ipykernel_1520/1402155349.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['public_record_bankruptcies'].fillna(0, inplace=True)

In [298]:
df['public_record_bankruptcies'].value_counts()

public_record_bankruptcies
0.0    350915
1.0     42790
2.0      1847
3.0       351
4.0        82
5.0        32
6.0         7
7.0         4
8.0         2
Name: count, dtype: int64

In [299]:
df.isnull().sum()

loan_amount_requested         0
term                          0
interest_rate                 0
installment                   0
assigned_loan_grade           0
assigned_loan_subgrade        0
occupation                    0
years_of_experience           0
home_ownership                0
annual_income                 0
verification_status           0
issued_month                  0
loan_status                   0
purpose                       0
title                         0
debt_to_income_ratio          0
earliest_cr_line              0
open_credit_lines             0
derogatory_public_records     0
revolving_credit_balance      0
revol_util                    0
total_acc                     0
initial_list_status           0
application_type              0
mortgage_accounts             0
public_record_bankruptcies    0
address                       0
city                          0
state                         0
zip_code                      0
dtype: int64