<a href="https://colab.research.google.com/github/akshaykumar2972/Banking-Data-Analysis/blob/main/Banking_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/content/logistic_regression.csv').drop_duplicates()
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,...,16.0,0.0,36369.0,41.8,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,...,17.0,0.0,20131.0,53.3,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,...,13.0,0.0,11987.0,92.2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,...,6.0,0.0,5472.0,21.5,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,...,13.0,0.0,24584.0,69.8,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

In [4]:
df.shape

(396030, 27)

In [5]:
df.iloc[:,:11].head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,Not Verified
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,Not Verified
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,Source Verified
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,Not Verified
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,Verified

In [6]:
df['loan_amnt'] = df['loan_amnt'].astype(int)

In [7]:
df['term'] = df['term'].apply(lambda x: int(x.split()[0]))

In [8]:
df['emp_length'] = df['emp_length'].replace({'< 1 year': '0.5 years', '10+ years': '12 years'})

In [9]:
df['emp_length'].value_counts()

emp_length
12 years     126041
2 years       35827
0.5 years     31725
3 years       31665
5 years       26495
1 year        25882
4 years       23952
6 years       20841
7 years       20819
8 years       19168
9 years       15314
Name: count, dtype: int64

In [10]:
df['emp_length'] = pd.to_numeric(df['emp_length'].str.extract(r'(\d+\.?\d*)')[0])

In [11]:
df.iloc[:,:11].head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status
0,10000,36,11.44,329.48,B,B4,Marketing,12.0,RENT,117000.0,Not Verified
1,8000,36,11.99,265.68,B,B5,Credit analyst,4.0,MORTGAGE,65000.0,Not Verified
2,15600,36,10.49,506.97,B,B3,Statistician,0.5,RENT,43057.0,Source Verified
3,7200,36,6.49,220.65,A,A2,Client Advocate,6.0,RENT,54000.0,Not Verified
4,24375,60,17.27,609.33,C,C5,Destiny Management Inc.,9.0,MORTGAGE,55000.0,Verified

In [12]:
df.iloc[:,11:20].head()

,issue_d,loan_status,purpose,title,dti,earliest_cr_line,open_acc,pub_rec,revol_bal
0,Jan-2015,Fully Paid,vacation,Vacation,26.24,Jun-1990,16.0,0.0,36369.0
1,Jan-2015,Fully Paid,debt_consolidation,Debt consolidation,22.05,Jul-2004,17.0,0.0,20131.0
2,Jan-2015,Fully Paid,credit_card,Credit card refinancing,12.79,Aug-2007,13.0,0.0,11987.0
3,Nov-2014,Fully Paid,credit_card,Credit card refinancing,2.60,Sep-2006,6.0,0.0,5472.0
4,Apr-2013,Charged Off,credit_card,Credit Card Refinance,33.95,Mar-1999,13.0,0.0,24584.0

In [64]:
df.rename(columns={'issue_d': 'issued_month'}, inplace=True)

In [28]:
df['purpose'].value_counts().reset_index()

               purpose   count
0   debt_consolidation  234507
1          credit_card   83019
2     home_improvement   24030
3                other   21185
4       major_purchase    8790
5       small_business    5701
6                  car    4697
7              medical    4196
8               moving    2854
9             vacation    2452
10               house    2201
11             wedding    1812
12    renewable_energy     329
13         educational     257

In [27]:
loan_title = df['title'].value_counts().reset_index()
loan_title[loan_title['count'] > 100]['title'].unique()

array(['Debt consolidation', 'Credit card refinancing',
       'Home improvement', 'Other', 'Debt Consolidation',
       'Major purchase', 'Consolidation', 'debt consolidation',
       'Business', 'Debt Consolidation Loan', 'Medical expenses',
       'Car financing', 'Credit Card Consolidation', 'Vacation',
       'Moving and relocation', 'consolidation', 'Personal Loan',
       'Consolidation Loan', 'Home Improvement', 'Home buying',
       'Credit Card Refinance', 'Credit Card Payoff', 'Consolidate',
       'Personal', 'Loan', 'Credit Card Loan', 'Freedom', 'consolidate',
       'personal', 'personal loan', 'Debt', 'home improvement', 'Payoff',
       'Credit Cards', 'payoff', 'Credit Card', 'DEBT CONSOLIDATION',
       'Home Improvement Loan', 'Debt Consolidation ',
       'credit card payoff', 'My Loan', 'Small Business Loan',
       'credit card consolidation', 'credit card refinance', 'Debt Free',
       'Refinance', 'Wedding', 'Wedding Loan', 'loan', 'debt',
       'CC Consolidation', 'Debt Loan', 'Credit Consolidation',
       'Credit card consolidation', 'credit cards', 'consolidation loan',
       'freedom', 'debt consolidation loan', 'credit card', 'Car Loan',
       'Credit Card Refi', 'Credit card payoff', 'Debt Payoff',
       'Personal loan', 'debt_consolidation', 'Debt consolidation loan',
       'Medical', 'Credit Card Debt Consolidation',
       'Credit card refinance', 'my loan', 'Debt consolidation ',
       'Consolidation loan', 'Credit Card Refinancing',
       'Bill Consolidation', 'Home', 'debt free', 'Lending Club',
       'Loan 1', 'Credit Card Debt', 'pay off credit cards',
       'Consolidation ', 'My loan', 'Credit cards', 'Bills', 'CC Payoff',
       'Lending Club Loan', 'Green loan', 'Loan Consolidation',
       'Pay off credit cards', 'pay off', 'Other Loan', 'Business Loan',
       'Major Purchase', 'Credit Card Pay Off', 'debt loan',
       'debt consolidation ', 'Major Purchase Loan', 'Pool', 'Pay Off',
       'Home Improvements', 'CC Loan', 'CC Refinance', 'Debt Consol',
       'Fresh Start', 'Credit Card Consolidation Loan', 'bills',
       'refinance', 'vacation', 'Wedding expenses', 'credit card pay off',
       'Debt Consolodation', 'CONSOLIDATION', 'Debt payoff', 'Debt free',
       'Moving Loan', 'credit card loan', 'Pool Loan', 'Medical Loan',
       'CC Refi', 'Pay off', 'debt payoff', 'Loan1', 'Freedom Loan',
       'Debt Reduction', 'home', 'wedding', 'Credit Card Refinance Loan',
       'Relief', 'credit card debt', 'Wedding Expenses', 'Moving',
       'Consolidate Debt', 'Debit Consolidation', 'Refi', 'Debt loan',
       'Debt Relief', 'Credit card', 'Credit'], dtype=object)

In [15]:
df.iloc[:,21:].head()

,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

In [29]:
df['application_type'].value_counts()

application_type
INDIVIDUAL    395319
JOINT            425
DIRECT_PAY       286
Name: count, dtype: int64

In [38]:
df['pub_rec_bankruptcies'].value_counts()

pub_rec_bankruptcies
0.0    350380
1.0     42790
2.0      1847
3.0       351
4.0        82
5.0        32
6.0         7
7.0         4
8.0         2
Name: count, dtype: int64

In [39]:
pd.set_option('display.max_colwidth', None)
df['address'].sample(25)

338440                        476 Berry Ways\r\nNealmouth, ND 48052
21433     952 Anderson Gateway Suite 372\r\nWilliamshaven, NE 00813
299870                  92902 Rhonda Mission\r\nFordhaven, ME 70466
46243               773 Kathleen Park Apt. 949\r\nMarkton, KS 05113
46609             807 Stone Shore Apt. 922\r\nJessicastad, TN 00813
251581                                  USS Coleman\r\nFPO AA 48052
335416                 77035 Johnston Square\r\nEast John, ME 86630
108515       4686 Shannon Lane Suite 510\r\nWest Brittany, MI 22690
44780                 68627 Jonathon Rest\r\nNicholasfort, OH 86630
131611                       7857 Ross Ridge\r\nWhiteside, LA 29597
254362        15452 Mary Courts Suite 984\r\nKimberlyview, MS 22690
373462          5638 Sharp Lights Suite 328\r\nHenrymouth, SC 70466
131160              388 Ryan Ports Suite 969\r\nAaronbury, WA 29597
288480     1810 Green Villages Suite 093\r\nCalvinborough, DC 48052
217442                   46949 Brandt Inlet\r\nSouth Lisa, NY 22690
173297                  67335 Paul Squares\r\nPort Alyssa, NC 48052
303689          26055 Taylor Square\r\nNorth Sabrinamouth, MI 29597
284983    344 Nelson Turnpike Suite 183\r\nPort Emmamouth, MA 48052
327355                           Unit 0336 Box 8626\r\nDPO AP 93700
158624                                USCGC Wallace\r\nFPO AA 00813
70323               4903 Sarah Corners\r\nMartinezchester, MI 48052
141453        6623 Jessica Drives Suite 003\r\nMonicaland, NE 30723
339848         0044 Randolph Groves Apt. 810\r\nRandyland, MA 00813
62861          2421 Tanya Centers Suite 492\r\nSouth Mary, DC 48052
180339                  2612 Maria Alley\r\nDavidsonmouth, WV 05113
Name: address, dtype: object

In [45]:
temp_split = df['address'].str.split('\n').str[1].str.split(',', expand=True)

df['city'] = temp_split[0].str.strip()
df['state'] = temp_split[1].str.strip().str.split(' ').str[0]
df['zip_code'] = temp_split[1].str.strip().str.split(' ').str[1]

In [50]:
df[['address','city','state','zip_code']].sample(25)

,address,city,state,zip_code
388374,"94151 Marie Ridge Apt. 701\r\nMendezfort, MA 29597",Mendezfort,MA,29597
98297,"5006 Kristen Lodge Apt. 996\r\nWest Thomasberg, WA 48052",West Thomasberg,WA,48052
260256,"6907 Anderson Islands Suite 294\r\nLake Stephanie, GA 22690",Lake Stephanie,GA,22690
368216,"24485 Golden Land\r\nWhiteland, ID 29597",Whiteland,ID,29597
101207,"67665 Cynthia Parkway Apt. 551\r\nLindsaymouth, NH 29597",Lindsaymouth,NH,29597
143499,"9689 Emily Passage\r\nJaystad, TN 48052",Jaystad,TN,48052
247117,"21097 Sandra Meadows Apt. 913\r\nFranciscohaven, MO 22690",Franciscohaven,MO,22690
107563,"809 Hernandez Pines Suite 345\r\nSouth Lisabury, MA 05113",South Lisabury,MA,05113
351911,"743 Butler Overpass Suite 014\r\nQuinnmouth, MI 48052",Quinnmouth,MI,48052
259140,"021 Melissa Spring Apt. 758\r\nDouglashaven, WA 11650",Douglashaven,WA,11650
264208,"229 Nicole Drive Suite 640\r\nLake Keith, MI 22690",Lake Keith,MI,22690
93686,"5145 Charles Isle\r\nEast Julia, AZ 70466",East Julia,AZ,70466
264892,"527 Kristin Spurs\r\nSouth Roger, WI 00813",South Roger,WI,00813
169015,"066 Ferguson Cape Suite 345\r\nBuchananfurt, OH 00813",Buchananfurt,OH,00813
46079,"06156 Linda Mountain\r\nNicholasshire, VT 48052",Nicholasshire,VT,48052
180525,Unit 3246 Box 6049\r\nDPO AE 00813,DPO AE 00813,None,None
82797,"2670 Jones Place\r\nEast Michael, NH 48052",East Michael,NH,48052
140141,"75520 Ryan Stream\r\nLake Roy, ND 48052",Lake Roy,ND,48052
38004,"075 John Valleys Suite 413\r\nLake Danielbury, MD 70466",Lake Danielbury,MD,70466
127230,"091 Adams Mills Suite 905\r\nNew Hectortown, NY 22690",New Hectortown,NY,22690
352624,"04596 Hall Street\r\nSanderschester, VT 70466",Sanderschester,VT,70466
232814,"094 Jennifer Common Suite 887\r\nBonniefort, WY 22690",Bonniefort,WY,22690
10148,"9643 Rice Ford\r\nQuinnbury, UT 48052",Quinnbury,UT,48052
27823,"62237 White Lock Apt. 258\r\nHeidiburgh, DE 00813",Heidiburgh,DE,00813
190792,"29464 Edwards Station\r\nLake Ravenshire, AR 29597",Lake Ravenshire,AR,29597

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 30 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   loan_amnt             396030 non-null  int64
 1   term                  396030 non-null  int64
 2   int_rate              396030 non-null  float64
 3   installment           396030 non-null  float64
 4   grade                 396030 non-null  object
 5   sub_grade             396030 non-null  object
 6   emp_title             373103 non-null  object
 7   emp_length            377729 non-null  float64
 8   home_ownership        396030 non-null  object
 9   annual_inc            396030 non-null  float64
 10  verification_status   396030 non-null  object
 11  issued_month          396030 non-null  object
 12  loan_status           396030 non-null  object
 13  purpose               396030 non-null  object
 14  title                 394274 non-null  object
 15  dti                   396030 non-null  float64
 16  earliest_cr_line      396030 non-null  object
 17  open_acc              396030 non-null  float64
 18  pub_rec               396030 non-null  float64
 19  revol_bal             396030 non-null  float64
 20  revol_util            395754 non-null  float64
 21  total_acc             396030 non-null  float64
 22  initial_list_status   396030 non-null  object
 23  application_type      396030 non-null  object
 24  mort_acc              358235 non-null  float64
 25  pub_rec_bankruptcies  395495 non-null  float64
 26  address               396030 non-null  object
 27  city                  396030 non-null  object
 28  state                 353646 non-null  object
 29  zip_code              353646 non-null  object
dtypes: float64(12), int64(2), object(16)
memory usage: 90.6+ MB

In [60]:
df.describe()

,loan_amnt,term,int_rate,installment,emp_length,annual_inc,dti,open_acc,pub_rec,revol_bal,revol_util,total_acc,mort_acc,pub_rec_bankruptcies
count,396030.000000,396030.000000,396030.000000,396030.000000,377729.000000,3.960300e+05,396030.000000,396030.000000,396030.000000,3.960300e+05,395754.000000,396030.000000,358235.000000,395495.000000
mean,14113.888089,41.698053,13.639400,431.849698,6.647934,7.420318e+04,17.379514,11.311153,0.178191,1.584454e+04,53.791749,25.414744,1.813991,0.121648
std,8357.441341,10.212038,4.472157,250.727790,4.366374,6.163762e+04,18.019092,5.137649,0.530671,2.059184e+04,24.452193,11.886991,2.147930,0.356174
min,500.000000,36.000000,5.320000,16.080000,0.500000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,2.000000,0.000000,0.000000
25%,8000.000000,36.000000,10.490000,250.330000,3.000000,4.500000e+04,11.280000,8.000000,0.000000,6.025000e+03,35.800000,17.000000,0.000000,0.000000
50%,12000.000000,36.000000,13.330000,375.430000,6.000000,6.400000e+04,16.910000,10.000000,0.000000,1.118100e+04,54.800000,24.000000,1.000000,0.000000
75%,20000.000000,36.000000,16.490000,567.300000,12.000000,9.000000e+04,22.980000,14.000000,0.000000,1.962000e+04,72.900000,32.000000,3.000000,0.000000
max,40000.000000,60.000000,30.990000,1533.810000,12.000000,8.706582e+06,9999.000000,90.000000,86.000000,1.743266e+06,892.300000,151.000000,34.000000,8.000000

In [61]:
df.describe(include='object')

,grade,sub_grade,emp_title,home_ownership,verification_status,issue_d,loan_status,purpose,title,earliest_cr_line,initial_list_status,application_type,address,city,state,zip_code
count,396030,396030,373103,396030,396030,396030,396030,396030,394274,396030,396030,396030,396030,396030,353646,353646
unique,7,35,173105,6,3,115,2,14,48816,684,2,3,393700,67600,51,10
top,B,B3,Teacher,MORTGAGE,Verified,Oct-2014,Fully Paid,debt_consolidation,Debt consolidation,Oct-2000,f,INDIVIDUAL,USS Johnson\r\nFPO AE 48052,APO AP 70466,NJ,70466
freq,116018,26655,4389,198348,139563,14846,318357,234507,152472,3017,238066,395319,8,757,7091,50859