<a href="https://colab.research.google.com/github/akshaykumar2972/Banking-Data-Analysis/blob/main/Banking_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Importing the required libraries**

In [127]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### **Importing the data from .CSV file**

In [128]:
df = pd.read_csv('/content/logistic_regression.csv').drop_duplicates()
df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,...,16.0,0.0,36369.0,41.8,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,...,17.0,0.0,20131.0,53.3,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,...,13.0,0.0,11987.0,92.2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,...,6.0,0.0,5472.0,21.5,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,...,13.0,0.0,24584.0,69.8,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

In [129]:
df.shape

(396030, 27)

In [130]:
df.iloc[:,:11].head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,Not Verified
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,Not Verified
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,Source Verified
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,Not Verified
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,Verified

In [131]:
df['loan_amnt'] = df['loan_amnt'].astype(int)

In [132]:
df['term'] = df['term'].apply(lambda x: int(x.split()[0]))

In [133]:
df['emp_length'] = df['emp_length'].replace({'< 1 year': '0.5 years', '10+ years': '12 years'})

In [134]:
df['emp_length'].value_counts()

emp_length
12 years     126041
2 years       35827
0.5 years     31725
3 years       31665
5 years       26495
1 year        25882
4 years       23952
6 years       20841
7 years       20819
8 years       19168
9 years       15314
Name: count, dtype: int64

In [135]:
df['emp_length'] = pd.to_numeric(df['emp_length'].str.extract(r'(\d+\.?\d*)')[0])

In [136]:
df.iloc[:,:11].head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status
0,10000,36,11.44,329.48,B,B4,Marketing,12.0,RENT,117000.0,Not Verified
1,8000,36,11.99,265.68,B,B5,Credit analyst,4.0,MORTGAGE,65000.0,Not Verified
2,15600,36,10.49,506.97,B,B3,Statistician,0.5,RENT,43057.0,Source Verified
3,7200,36,6.49,220.65,A,A2,Client Advocate,6.0,RENT,54000.0,Not Verified
4,24375,60,17.27,609.33,C,C5,Destiny Management Inc.,9.0,MORTGAGE,55000.0,Verified

In [137]:
df.rename(columns={'loan_amnt':'loan_amount_requested'
                  ,'int_rate':'interest_rate'
                  ,'grade':'assigned_loan_grade'
                  ,'sub_grade':'assigned_loan_subgrade'
                  ,'emp_title':'occupation'
                  ,'emp_length':'years_of_experience'
                  ,'annual_inc':'annual_income'}, inplace=True)

In [138]:
df.iloc[:,11:20].head()

,issue_d,loan_status,purpose,title,dti,earliest_cr_line,open_acc,pub_rec,revol_bal
0,Jan-2015,Fully Paid,vacation,Vacation,26.24,Jun-1990,16.0,0.0,36369.0
1,Jan-2015,Fully Paid,debt_consolidation,Debt consolidation,22.05,Jul-2004,17.0,0.0,20131.0
2,Jan-2015,Fully Paid,credit_card,Credit card refinancing,12.79,Aug-2007,13.0,0.0,11987.0
3,Nov-2014,Fully Paid,credit_card,Credit card refinancing,2.60,Sep-2006,6.0,0.0,5472.0
4,Apr-2013,Charged Off,credit_card,Credit Card Refinance,33.95,Mar-1999,13.0,0.0,24584.0

In [139]:
df.rename(columns={'issue_d':'issued_month'
                  ,'open_acc':'open_credit_lines'
                  ,'dti':'debt_to_income_ratio'
                  ,'earliest_cr_line':'earliest_credit_line_date'
                  ,'pub_rec':'derogatory_public_records'
                  ,'revol_bal':'revolving_credit_balance'}, inplace=True)

In [140]:
df['purpose'].value_counts().reset_index()

               purpose   count
0   debt_consolidation  234507
1          credit_card   83019
2     home_improvement   24030
3                other   21185
4       major_purchase    8790
5       small_business    5701
6                  car    4697
7              medical    4196
8               moving    2854
9             vacation    2452
10               house    2201
11             wedding    1812
12    renewable_energy     329
13         educational     257

In [141]:
loan_title = df['title'].value_counts().reset_index()
loan_title[loan_title['count'] > 100]['title'].unique()

array(['Debt consolidation', 'Credit card refinancing',
       'Home improvement', 'Other', 'Debt Consolidation',
       'Major purchase', 'Consolidation', 'debt consolidation',
       'Business', 'Debt Consolidation Loan', 'Medical expenses',
       'Car financing', 'Credit Card Consolidation', 'Vacation',
       'Moving and relocation', 'consolidation', 'Personal Loan',
       'Consolidation Loan', 'Home Improvement', 'Home buying',
       'Credit Card Refinance', 'Credit Card Payoff', 'Consolidate',
       'Personal', 'Loan', 'Credit Card Loan', 'Freedom', 'consolidate',
       'personal', 'personal loan', 'Debt', 'home improvement', 'Payoff',
       'Credit Cards', 'payoff', 'Credit Card', 'DEBT CONSOLIDATION',
       'Home Improvement Loan', 'Debt Consolidation ',
       'credit card payoff', 'My Loan', 'Small Business Loan',
       'credit card consolidation', 'credit card refinance', 'Debt Free',
       'Refinance', 'Wedding', 'Wedding Loan', 'loan', 'debt',
       'CC Consolidation', 'Debt Loan', 'Credit Consolidation',
       'Credit card consolidation', 'credit cards', 'consolidation loan',
       'freedom', 'debt consolidation loan', 'credit card', 'Car Loan',
       'Credit Card Refi', 'Credit card payoff', 'Debt Payoff',
       'Personal loan', 'debt_consolidation', 'Debt consolidation loan',
       'Medical', 'Credit Card Debt Consolidation',
       'Credit card refinance', 'my loan', 'Debt consolidation ',
       'Consolidation loan', 'Credit Card Refinancing',
       'Bill Consolidation', 'Home', 'debt free', 'Lending Club',
       'Loan 1', 'Credit Card Debt', 'pay off credit cards',
       'Consolidation ', 'My loan', 'Credit cards', 'Bills', 'CC Payoff',
       'Lending Club Loan', 'Green loan', 'Loan Consolidation',
       'Pay off credit cards', 'pay off', 'Other Loan', 'Business Loan',
       'Major Purchase', 'Credit Card Pay Off', 'debt loan',
       'debt consolidation ', 'Major Purchase Loan', 'Pool', 'Pay Off',
       'Home Improvements', 'CC Loan', 'CC Refinance', 'Debt Consol',
       'Fresh Start', 'Credit Card Consolidation Loan', 'bills',
       'refinance', 'vacation', 'Wedding expenses', 'credit card pay off',
       'Debt Consolodation', 'CONSOLIDATION', 'Debt payoff', 'Debt free',
       'Moving Loan', 'credit card loan', 'Pool Loan', 'Medical Loan',
       'CC Refi', 'Pay off', 'debt payoff', 'Loan1', 'Freedom Loan',
       'Debt Reduction', 'home', 'wedding', 'Credit Card Refinance Loan',
       'Relief', 'credit card debt', 'Wedding Expenses', 'Moving',
       'Consolidate Debt', 'Debit Consolidation', 'Refi', 'Debt loan',
       'Debt Relief', 'Credit card', 'Credit'], dtype=object)

In [142]:
df.iloc[:,21:].head()

,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

In [143]:
df['application_type'].value_counts()

application_type
INDIVIDUAL    395319
JOINT            425
DIRECT_PAY       286
Name: count, dtype: int64

In [144]:
df.rename(columns={'mort_acc':'mortgage_accounts', 'pub_rec_bankruptcies':'public_record_bankruptcies'}, inplace=True)

In [145]:
df['public_record_bankruptcies'].value_counts()

public_record_bankruptcies
0.0    350380
1.0     42790
2.0      1847
3.0       351
4.0        82
5.0        32
6.0         7
7.0         4
8.0         2
Name: count, dtype: int64

In [146]:
pd.set_option('display.max_colwidth', None)
df['address'].sample(25)

219316              16792 Raymond Lights\r\nLake Waynehaven, SC 48052
114834                  50700 Cox Valley\r\nNorth Beckyport, LA 29597
342807               346 Lori Neck Apt. 433\r\nAlexandraton, AZ 48052
172082               782 James Brook Suite 512\r\nWellsfurt, GA 70466
284705              98451 Jessica Valley\r\nNorth Christina, KS 22690
109568              421 Brianna Loaf Suite 535\r\nSmithside, IN 48052
196615                    6817 Reyes Gardens\r\nEast Thomas, PA 93700
161433                       35974 Brian Spur\r\nGarciafurt, NJ 48052
368971        1880 Ortega Overpass Suite 854\r\nNicolemouth, VA 22690
31785                              Unit 2379 Box 9552\r\nDPO AE 00813
342694                                  USNV Mcintosh\r\nFPO AP 30723
14310                       87747 Holland Keys\r\nKevinberg, RI 70466
246350       6874 Dixon Turnpike Apt. 476\r\nNew Robertfort, AK 70466
139911           535 Zachary Dale Suite 656\r\nThompsonport, CO 48052
387279                      527 Cynthia Brook\r\nVincentton, WI 22690
286366                       3118 Emily Via\r\nGonzalezfort, ID 29597
207406              3891 Mills Valley Suite 271\r\nNew Alex, ND 05113
265119                             Unit 5754 Box 1434\r\nDPO AE 05113
244833                                     USNV Clark\r\nFPO AA 70466
285327                             PSC 5937, Box 3968\r\nAPO AP 30723
330028                   509 Rice Way Suite 536\r\nLisaberg, VA 30723
137777                             PSC 2356, Box 6554\r\nAPO AE 48052
236160                8272 Payne Extensions\r\nNavarroshire, NY 70466
301220       3359 Anthony Fall Apt. 126\r\nNew Michaelmouth, ID 11650
4641      0204 Jensen Terrace Suite 429\r\nLake Brandishire, OR 70466
Name: address, dtype: object

In [147]:
temp_split = df['address'].str.split('\n').str[1].str.split(',', expand=True)

df['city'] = temp_split[0].str.strip()
df['state'] = temp_split[1].str.strip().str.split(' ').str[0]
df['zip_code'] = temp_split[1].str.strip().str.split(' ').str[1]

In [148]:
df[['address','city','state','zip_code']].sample(25)

,address,city,state,zip_code
49042,"4345 Heather Row\r\nJessicashire, ME 05113",Jessicashire,ME,05113
167381,"564 Hunt Manor Suite 184\r\nFoxstad, UT 00813",Foxstad,UT,00813
288501,"03858 Michael Grove\r\nLake Aaronfurt, AL 30723",Lake Aaronfurt,AL,30723
220262,"0260 Strickland Avenue Apt. 551\r\nNorth Johnhaven, VA 30723",North Johnhaven,VA,30723
172582,"1257 Billy Crest Suite 558\r\nLake Tammyfurt, NH 11650",Lake Tammyfurt,NH,11650
42719,"5071 Ford Mountains Suite 639\r\nSpencerland, SC 30723",Spencerland,SC,30723
100965,"07404 Laura Valleys Apt. 830\r\nEast Nancystad, MI 00813",East Nancystad,MI,00813
281546,"07859 Marissa Rapids Suite 230\r\nPort Chris, TX 11650",Port Chris,TX,11650
262585,"7424 Frederick Lock\r\nLake Jamesfurt, WA 70466",Lake Jamesfurt,WA,70466
168040,"65987 Lee Vista Apt. 105\r\nWest Elizabethhaven, AZ 05113",West Elizabethhaven,AZ,05113
34456,"972 Gilbert Ford Suite 692\r\nGrahamfurt, HI 70466",Grahamfurt,HI,70466
116704,"6406 French Roads\r\nSouth Marvin, WV 29597",South Marvin,WV,29597
195514,"399 Erin Pines Apt. 058\r\nLake Ericaside, VA 29597",Lake Ericaside,VA,29597
24612,"945 Marks Square Suite 428\r\nIngrammouth, IL 00813",Ingrammouth,IL,00813
280034,"8853 Ferguson Loaf Apt. 307\r\nEast Justin, OK 22690",East Justin,OK,22690
144466,"665 Mills Keys Apt. 565\r\nHannahfurt, MN 05113",Hannahfurt,MN,05113
337575,"70171 Stephen Union\r\nEast Kimberlyfort, GA 05113",East Kimberlyfort,GA,05113
86257,"142 Wade Haven Apt. 071\r\nJosephville, NJ 29597",Josephville,NJ,29597
297181,"31579 Conrad Inlet Suite 323\r\nWest Thomas, NJ 93700",West Thomas,NJ,93700
192557,"PSC 9280, Box 1096\r\nAPO AE 48052",APO AE 48052,None,None
81505,"600 Robert Divide Apt. 029\r\nNew Douglaschester, OH 11650",New Douglaschester,OH,11650
292367,"65870 James Harbors Suite 847\r\nNorth Jennifer, NV 30723",North Jennifer,NV,30723
330039,"396 Brandon Ford\r\nEast Davidberg, UT 00813",East Davidberg,UT,00813
209056,"49295 Robinson Haven\r\nLake Taylorport, MT 86630",Lake Taylorport,MT,86630
314162,"97004 Lester Ports Suite 360\r\nLake Katherinestad, FL 70466",Lake Katherinestad,FL,70466

In [149]:
df[df.index == 180525]

,loan_amount_requested,term,interest_rate,installment,assigned_loan_grade,assigned_loan_subgrade,occupation,years_of_experience,home_ownership,annual_income,...,revol_util,total_acc,initial_list_status,application_type,mortgage_accounts,public_record_bankruptcies,address,city,state,zip_code
180525,24000,36,6.03,730.46,A,A1,"VP, Senior Analyst",8.0,MORTGAGE,150000.0,...,41.8,19.0,w,INDIVIDUAL,2.0,0.0,Unit 3246 Box 6049\r\nDPO AE 00813,DPO AE 00813,None,None

In [150]:
df[df['state'].isna()]['city'].unique()

array(['FPO AE 30723', 'FPO AP 22690', 'DPO AE 05113', 'DPO AE 48052',
       'FPO AA 30723', 'APO AP 05113', 'APO AA 22690', 'FPO AE 22690',
       'FPO AA 48052', 'DPO AE 29597', 'FPO AP 29597', 'FPO AE 05113',
       'FPO AP 30723', 'DPO AE 86630', 'APO AP 29597', 'DPO AP 30723',
       'FPO AP 00813', 'FPO AA 11650', 'APO AP 11650', 'APO AA 48052',
       'APO AE 48052', 'DPO AA 29597', 'DPO AP 48052', 'FPO AE 00813',
       'DPO AA 30723', 'APO AA 30723', 'FPO AA 29597', 'APO AA 70466',
       'APO AE 29597', 'DPO AA 22690', 'APO AE 00813', 'FPO AA 70466',
       'DPO AE 93700', 'APO AE 05113', 'FPO AE 48052', 'DPO AP 00813',
       'APO AA 11650', 'APO AE 11650', 'APO AP 22690', 'APO AE 30723',
       'FPO AE 70466', 'DPO AP 29597', 'APO AE 70466', 'FPO AA 22690',
       'FPO AE 29597', 'DPO AE 30723', 'DPO AP 70466', 'FPO AA 05113',
       'DPO AE 22690', 'APO AE 22690', 'DPO AE 00813', 'APO AP 00813',
       'DPO AA 48052', 'DPO AE 70466', 'APO AA 00813', 'APO AA 86630',
       'APO AA 29597', 'APO AA 05113', 'DPO AP 86630', 'DPO AP 93700',
       'APO AP 70466', 'FPO AP 48052', 'FPO AP 70466', 'DPO AA 00813',
       'FPO AA 00813', 'DPO AP 11650', 'DPO AP 22690', 'FPO AP 05113',
       'FPO AA 86630', 'DPO AE 11650', 'APO AP 48052', 'APO AP 30723',
       'FPO AP 86630', 'DPO AA 70466', 'APO AP 93700', 'DPO AA 05113',
       'DPO AA 86630', 'APO AA 93700', 'APO AE 93700', 'DPO AP 05113',
       'APO AP 86630', 'APO AE 86630', 'FPO AP 11650', 'FPO AP 93700',
       'DPO AA 93700', 'DPO AA 11650', 'FPO AE 86630', 'FPO AA 93700',
       'FPO AE 11650', 'FPO AE 93700'], dtype=object)

In [151]:
missing_state = df[df['state'].isna()]
extracted = missing_state['city'].str.extract(r'(?P<c>APO|FPO|DPO)\s+(?P<s>[A-Z]{2})\s+(?P<z>\d{5})')
extracted

          c   s      z
7       FPO  AE  30723
8       FPO  AP  22690
19      DPO  AE  05113
26      DPO  AE  48052
33      FPO  AA  30723
...     ...  ..    ...
395995  APO  AP  22690
395997  APO  AP  22690
396010  APO  AA  05113
396012  DPO  AP  29597
396015  DPO  AA  05113

[42384 rows x 3 columns]

In [152]:
df.loc[missing_state.index, 'city'] = extracted['c']
df.loc[missing_state.index, 'state'] = extracted['s']
df.loc[missing_state.index, 'zip_code'] = extracted['z']

In [153]:
df['city'] = df['city'].str.strip()
df['state'] = df['state'].str.strip()

In [154]:
df['zip_code'].unique()

array(['22690', '05113', '00813', '11650', '30723', '70466', '29597',
       '48052', '86630', '93700'], dtype=object)

In [155]:
df[df['state'].isna()]

Empty DataFrame
Columns: [loan_amount_requested, term, interest_rate, installment, assigned_loan_grade, assigned_loan_subgrade, occupation, years_of_experience, home_ownership, annual_income, verification_status, issued_month, loan_status, purpose, title, debt_to_income_ratio, earliest_credit_line_date, open_credit_lines, derogatory_public_records, revolving_credit_balance, revol_util, total_acc, initial_list_status, application_type, mortgage_accounts, public_record_bankruptcies, address, city, state, zip_code]
Index: []

[0 rows x 30 columns]

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396030 entries, 0 to 396029
Data columns (total 30 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   loan_amount_requested       396030 non-null  int64
 1   term                        396030 non-null  int64
 2   interest_rate               396030 non-null  float64
 3   installment                 396030 non-null  float64
 4   assigned_loan_grade         396030 non-null  object
 5   assigned_loan_subgrade      396030 non-null  object
 6   occupation                  373103 non-null  object
 7   years_of_experience         377729 non-null  float64
 8   home_ownership              396030 non-null  object
 9   annual_income               396030 non-null  float64
 10  verification_status         396030 non-null  object
 11  issued_month                396030 non-null  object
 12  loan_status                 396030 non-null  object
 13  purpose                     396030 non-null  object
 14  title                       394274 non-null  object
 15  debt_to_income_ratio        396030 non-null  float64
 16  earliest_credit_line_date   396030 non-null  object
 17  open_credit_lines           396030 non-null  float64
 18  derogatory_public_records   396030 non-null  float64
 19  revolving_credit_balance    396030 non-null  float64
 20  revol_util                  395754 non-null  float64
 21  total_acc                   396030 non-null  float64
 22  initial_list_status         396030 non-null  object
 23  application_type            396030 non-null  object
 24  mortgage_accounts           358235 non-null  float64
 25  public_record_bankruptcies  395495 non-null  float64
 26  address                     396030 non-null  object
 27  city                        396030 non-null  object
 28  state                       396030 non-null  object
 29  zip_code                    396030 non-null  object
dtypes: float64(12), int64(2), object(16)
memory usage: 90.6+ MB

In [157]:
df.describe()

,loan_amount_requested,term,interest_rate,installment,years_of_experience,annual_income,debt_to_income_ratio,open_credit_lines,derogatory_public_records,revolving_credit_balance,revol_util,total_acc,mortgage_accounts,public_record_bankruptcies
count,396030.000000,396030.000000,396030.000000,396030.000000,377729.000000,3.960300e+05,396030.000000,396030.000000,396030.000000,3.960300e+05,395754.000000,396030.000000,358235.000000,395495.000000
mean,14113.888089,41.698053,13.639400,431.849698,6.647934,7.420318e+04,17.379514,11.311153,0.178191,1.584454e+04,53.791749,25.414744,1.813991,0.121648
std,8357.441341,10.212038,4.472157,250.727790,4.366374,6.163762e+04,18.019092,5.137649,0.530671,2.059184e+04,24.452193,11.886991,2.147930,0.356174
min,500.000000,36.000000,5.320000,16.080000,0.500000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,2.000000,0.000000,0.000000
25%,8000.000000,36.000000,10.490000,250.330000,3.000000,4.500000e+04,11.280000,8.000000,0.000000,6.025000e+03,35.800000,17.000000,0.000000,0.000000
50%,12000.000000,36.000000,13.330000,375.430000,6.000000,6.400000e+04,16.910000,10.000000,0.000000,1.118100e+04,54.800000,24.000000,1.000000,0.000000
75%,20000.000000,36.000000,16.490000,567.300000,12.000000,9.000000e+04,22.980000,14.000000,0.000000,1.962000e+04,72.900000,32.000000,3.000000,0.000000
max,40000.000000,60.000000,30.990000,1533.810000,12.000000,8.706582e+06,9999.000000,90.000000,86.000000,1.743266e+06,892.300000,151.000000,34.000000,8.000000

In [158]:
df.describe(include='object')

,assigned_loan_grade,assigned_loan_subgrade,occupation,home_ownership,verification_status,issued_month,loan_status,purpose,title,earliest_credit_line_date,initial_list_status,application_type,address,city,state,zip_code
count,396030,396030,373103,396030,396030,396030,396030,396030,394274,396030,396030,396030,396030,396030,396030,396030
unique,7,35,173105,6,3,115,2,14,48816,684,2,3,393700,67513,54,10
top,B,B3,Teacher,MORTGAGE,Verified,Oct-2014,Fully Paid,debt_consolidation,Debt consolidation,Oct-2000,f,INDIVIDUAL,USS Johnson\r\nFPO AE 48052,DPO,AP,70466
freq,116018,26655,4389,198348,139563,14846,318357,234507,152472,3017,238066,395319,8,14289,14308,56985

### **Handling NULL values**

In [159]:
df.isnull().sum()

loan_amount_requested             0
term                              0
interest_rate                     0
installment                       0
assigned_loan_grade               0
assigned_loan_subgrade            0
occupation                    22927
years_of_experience           18301
home_ownership                    0
annual_income                     0
verification_status               0
issued_month                      0
loan_status                       0
purpose                           0
title                          1756
debt_to_income_ratio              0
earliest_credit_line_date         0
open_credit_lines                 0
derogatory_public_records         0
revolving_credit_balance          0
revol_util                      276
total_acc                         0
initial_list_status               0
application_type                  0
mortgage_accounts             37795
public_record_bankruptcies      535
address                           0
city                              0
state                             0
zip_code                          0
dtype: int64

In [160]:
df['occupation'].fillna('Unspecified', inplace=True)

/tmp/ipykernel_238/933367638.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['occupation'].fillna('Unspecified', inplace=True)

In [161]:
median_val = df['years_of_experience'].median()
df['years_of_experience'] = df['years_of_experience'].fillna(median_val)

In [162]:
df.iloc[:,11:20][df['title'].isna()].sample(25)

,issued_month,loan_status,purpose,title,debt_to_income_ratio,earliest_credit_line_date,open_credit_lines,derogatory_public_records,revolving_credit_balance
216082,Jul-2016,Fully Paid,debt_consolidation,NaN,17.35,Feb-2003,15.0,0.0,14922.0
153907,Jan-2016,Charged Off,small_business,NaN,3.76,Nov-2001,14.0,0.0,5774.0
393334,Mar-2016,Fully Paid,credit_card,NaN,16.90,Sep-1996,11.0,0.0,20732.0
348337,Jan-2016,Fully Paid,credit_card,NaN,20.54,Jan-2001,7.0,0.0,18601.0
134343,Jan-2016,Charged Off,medical,NaN,0.79,Jul-1977,11.0,0.0,4404.0
294897,Apr-2016,Fully Paid,debt_consolidation,NaN,7.48,Oct-1988,4.0,0.0,20289.0
325589,May-2016,Fully Paid,debt_consolidation,NaN,16.16,Dec-2007,6.0,0.0,1054.0
96630,Feb-2016,Fully Paid,debt_consolidation,NaN,33.09,Oct-2006,8.0,1.0,4506.0
140310,May-2016,Fully Paid,debt_consolidation,NaN,15.28,Jun-2000,6.0,0.0,3708.0
363668,Jul-2016,Fully Paid,debt_consolidation,NaN,13.67,Jul-2004,6.0,1.0,1419.0
85727,Feb-2016,Fully Paid,debt_consolidation,NaN,36.93,May-2003,11.0,1.0,20537.0
11975,Feb-2016,Charged Off,debt_consolidation,NaN,33.59,Sep-2004,19.0,0.0,17360.0
129289,Jan-2016,Fully Paid,debt_consolidation,NaN,26.74,May-2007,11.0,0.0,11613.0
64414,Mar-2016,Fully Paid,debt_consolidation,NaN,33.00,Nov-2001,6.0,1.0,2974.0
394228,Apr-2016,Fully Paid,other,NaN,18.99,Mar-2004,22.0,0.0,13677.0
127808,Apr-2016,Fully Paid,credit_card,NaN,22.71,May-2007,16.0,0.0,13130.0
358200,Apr-2016,Fully Paid,debt_consolidation,NaN,16.32,Oct-2000,17.0,0.0,3370.0
338310,Mar-2016,Charged Off,debt_consolidation,NaN,28.99,Nov-2005,14.0,0.0,39920.0
155551,Feb-2016,Charged Off,credit_card,NaN,37.38,Dec-2011,12.0,0.0,19624.0
26280,Feb-2016,Charged Off,other,NaN,24.80,Oct-1997,10.0,0.0,18345.0
228140,Aug-2016,Fully Paid,debt_consolidation,NaN,14.90,Aug-2003,5.0,0.0,12230.0
181341,Sep-2016,Fully Paid,debt_consolidation,NaN,15.95,Dec-2004,17.0,0.0,18688.0
284452,Feb-2016,Fully Paid,debt_consolidation,NaN,9.47,Feb-1982,7.0,0.0,5261.0
247131,Aug-2016,Fully Paid,debt_consolidation,NaN,31.04,Apr-1995,10.0,0.0,19843.0
272681,Jan-2016,Fully Paid,debt_consolidation,NaN,17.15,Nov-2008,8.0,0.0,5975.0

In [163]:
df[df['title'].isna()]['purpose'].unique()

array(['debt_consolidation', 'credit_card', 'other', 'small_business',
       'home_improvement', 'medical', 'major_purchase', 'house', 'moving',
       'vacation', 'car', 'educational', 'renewable_energy'], dtype=object)

In [164]:
df['title'].fillna('Loan_reason_not_specified', inplace=True)

/tmp/ipykernel_238/2530785282.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['title'].fillna('Loan_reason_not_specified', inplace=True)

In [165]:
df[df['revol_util'].isna()][['total_acc', 'open_credit_lines', 'revolving_credit_balance', 'revol_util']].sample(25)

        total_acc  open_credit_lines  revolving_credit_balance  revol_util
90519        20.0                4.0                    2937.0         NaN
247987       24.0                4.0                       0.0         NaN
395088       10.0                6.0                       0.0         NaN
259133       13.0                3.0                       0.0         NaN
341221       26.0                6.0                  146843.0         NaN
141783       29.0                4.0                       0.0         NaN
251046       20.0                3.0                       0.0         NaN
127579       56.0                9.0                    5330.0         NaN
33284        12.0                4.0                   41345.0         NaN
341016       22.0                4.0                       0.0         NaN
219745       23.0                2.0                       0.0         NaN
107184       19.0                0.0                       0.0         NaN
58173        27.0                9.0                   15304.0         NaN
260510       16.0                6.0                   33191.0         NaN
54020        18.0                4.0                       0.0         NaN
287185        5.0                2.0                       0.0         NaN
221284       16.0                3.0                   42546.0         NaN
91407        18.0                4.0                     596.0         NaN
207406       32.0                9.0                       0.0         NaN
256663       22.0                5.0                   49238.0         NaN
150460       25.0               11.0                       0.0         NaN
84933        19.0                4.0                       0.0         NaN
203447        3.0                2.0                       0.0         NaN
239931       12.0                5.0                       0.0         NaN
28582        24.0                7.0                       0.0         NaN

In [166]:
# Updated query using your actual column names
# We'll check revolving_credit_balance and open_credit_lines to investigate the NaNs
df[df['revol_util'].isna()][['revolving_credit_balance', 'revol_util', 'open_credit_lines', 'total_acc']].sample(25)

        revolving_credit_balance  revol_util  open_credit_lines  total_acc
54767                    35123.0         NaN                9.0       42.0
214451                       0.0         NaN                3.0        9.0
58026                        0.0         NaN                5.0       11.0
90519                     2937.0         NaN                4.0       20.0
395665                       0.0         NaN                3.0       25.0
219448                       0.0         NaN                5.0       29.0
379968                       0.0         NaN               12.0       27.0
109523                       0.0         NaN                4.0       28.0
214643                       0.0         NaN                8.0       32.0
202629                       0.0         NaN                3.0       18.0
163695                   21400.0         NaN                8.0       55.0
219059                       0.0         NaN                3.0       13.0
69710                        0.0         NaN                4.0       18.0
230584                       0.0         NaN                2.0        5.0
178566                       0.0         NaN                5.0       26.0
263000                    1104.0         NaN                3.0       17.0
127579                    5330.0         NaN                9.0       56.0
218079                   56071.0         NaN                6.0       18.0
193783                       0.0         NaN                1.0       15.0
159591                       0.0         NaN                7.0        9.0
202463                       0.0         NaN                3.0       21.0
292115                       0.0         NaN                6.0        7.0
304417                       0.0         NaN                7.0       34.0
218140                  177665.0         NaN                7.0       29.0
81151                        0.0         NaN                5.0       24.0

In [167]:
# 1. Calculate the median for revol_util
revol_median = df['revol_util'].median()

# 2. Case A: Balance is 0 -> Utilization is 0
# We target rows where revol_util is NaN AND balance is 0
zero_bal_mask = (df['revol_util'].isna()) & (df['revolving_credit_balance'] == 0)
df.loc[zero_bal_mask, 'revol_util'] = 0

# 3. Case B: Balance > 0 but util is NaN (like row 33284) -> Fill with Median
# This handles the remaining NaNs in one go
df['revol_util'] = df['revol_util'].fillna(revol_median)

# 4. Final Cleanup: Remove those \r\n characters from the address column
# This will make your first image's output look much cleaner
df['address'] = df['address'].str.replace(r'\r\n', ' ', regex=True)

In [168]:
# Verify no nulls remain in revol_util
print(f"Remaining nulls in revol_util: {df['revol_util'].isna().sum()}")

# Check that high balance row specifically
print(df.loc[[33284], ['revolving_credit_balance', 'revol_util']])

Remaining nulls in revol_util: 0
       revolving_credit_balance  revol_util
33284                   41345.0        54.8

In [169]:
df['mortgage_accounts'].fillna(0, inplace=True)
df['public_record_bankruptcies'].fillna(0, inplace=True)

/tmp/ipykernel_238/1402155349.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['mortgage_accounts'].fillna(0, inplace=True)
/tmp/ipykernel_238/1402155349.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['public_record_bankruptcies'].fillna(0, inplace=True)

In [170]:
df['public_record_bankruptcies'].value_counts()

public_record_bankruptcies
0.0    350915
1.0     42790
2.0      1847
3.0       351
4.0        82
5.0        32
6.0         7
7.0         4
8.0         2
Name: count, dtype: int64

In [171]:
df.isnull().sum()

loan_amount_requested         0
term                          0
interest_rate                 0
installment                   0
assigned_loan_grade           0
assigned_loan_subgrade        0
occupation                    0
years_of_experience           0
home_ownership                0
annual_income                 0
verification_status           0
issued_month                  0
loan_status                   0
purpose                       0
title                         0
debt_to_income_ratio          0
earliest_credit_line_date     0
open_credit_lines             0
derogatory_public_records     0
revolving_credit_balance      0
revol_util                    0
total_acc                     0
initial_list_status           0
application_type              0
mortgage_accounts             0
public_record_bankruptcies    0
address                       0
city                          0
state                         0
zip_code                      0
dtype: int64

### **EDA**

In [172]:
df.iloc[:,:10].head()

,loan_amount_requested,term,interest_rate,installment,assigned_loan_grade,assigned_loan_subgrade,occupation,years_of_experience,home_ownership,annual_income
0,10000,36,11.44,329.48,B,B4,Marketing,12.0,RENT,117000.0
1,8000,36,11.99,265.68,B,B5,Credit analyst,4.0,MORTGAGE,65000.0
2,15600,36,10.49,506.97,B,B3,Statistician,0.5,RENT,43057.0
3,7200,36,6.49,220.65,A,A2,Client Advocate,6.0,RENT,54000.0
4,24375,60,17.27,609.33,C,C5,Destiny Management Inc.,9.0,MORTGAGE,55000.0

In [173]:
df.iloc[:,11:20].head()

,issued_month,loan_status,purpose,title,debt_to_income_ratio,earliest_credit_line_date,open_credit_lines,derogatory_public_records,revolving_credit_balance
0,Jan-2015,Fully Paid,vacation,Vacation,26.24,Jun-1990,16.0,0.0,36369.0
1,Jan-2015,Fully Paid,debt_consolidation,Debt consolidation,22.05,Jul-2004,17.0,0.0,20131.0
2,Jan-2015,Fully Paid,credit_card,Credit card refinancing,12.79,Aug-2007,13.0,0.0,11987.0
3,Nov-2014,Fully Paid,credit_card,Credit card refinancing,2.60,Sep-2006,6.0,0.0,5472.0
4,Apr-2013,Charged Off,credit_card,Credit Card Refinance,33.95,Mar-1999,13.0,0.0,24584.0

In [174]:
df.iloc[:,21:].head()

,total_acc,initial_list_status,application_type,mortgage_accounts,public_record_bankruptcies,address,city,state,zip_code
0,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway Mendozaberg, OK 22690",Mendozaberg,OK,22690
1,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347 Loganmouth, SD 05113",Loganmouth,SD,05113
2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269 New Sabrina, WV 05113",New Sabrina,WV,05113
3,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford Delacruzside, MA 00813",Delacruzside,MA,00813
4,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads Greggshire, VA 11650",Greggshire,VA,11650

In [ ]:
for i in df.columns:
  print(", ", "'", i, "'", sep='')

### **Encoding**

In [ ]:
columns_to_encode = [#'loan_amount_requested' -- numerical column
                  #, 'term' -- numerical column
                  #, 'interest_rate' -- numerical column
                  #, 'installment' -- numerical column
                  'assigned_loan_grade'
                  #, 'assigned_loan_subgrade' -- too many categories and the gist is captured in the assigned_loan_grade field
                  #, 'occupation' -- too many categories
                  #, 'years_of_experience' -- numerical column
                  , 'home_ownership'
                  #, 'annual_income' -- numerical column
                  , 'verification_status'
                  #, 'issued_month'
                  , 'loan_status'
                  , 'purpose'
                  #, 'title' -- too many categories
                  #, 'debt_to_income_ratio' -- numerical column
                  #, 'earliest_credit_line_date' -- numerical column
                  #, 'open_credit_lines' -- numerical column
                  #, 'derogatory_public_records' -- numerical column
                  #, 'revolving_credit_balance' -- numerical column
                  #, 'revol_util' -- numerical column
                  #, 'total_acc' -- numerical column
                  , 'initial_list_status'
                  , 'application_type'
                  #, 'mortgage_accounts' -- numerical column
                  #, 'public_record_bankruptcies' -- numerical column
                  #, 'address' -- too many categories
                  #, 'city' -- too many categories
                  #, 'state' -- too many categories
                  #, 'zip_code' -- not significant
                  ]
print(columns_to_encode)

In [ ]:
for i in columns_to_encode:
  print("the categories in", i, "are", df[i].unique())

In [ ]:
df_encoded = df.copy()
df_encoded.head()

In [ ]:
df_encoded.columns

In [ ]:
grade_map = {'A': 7, 'B': 6, 'C': 5, 'D': 4, 'E': 3, 'F': 2, 'G': 1}
df_encoded['assigned_loan_grade'] = df_encoded['assigned_loan_grade'].map(grade_map)

verify_map = {'Not Verified': 0, 'Source Verified': 1, 'Verified': 2}
df_encoded['verification_status'] = df_encoded['verification_status'].map(verify_map)

df_encoded['loan_status'] = df_encoded['loan_status'].map({'Fully Paid': 0, 'Charged Off': 1})

df_encoded['initial_list_status'] = df_encoded['initial_list_status'].map({'w': 0, 'f': 1})

nominal_cols = ['home_ownership', 'application_type', 'zip_code']
df_encoded = pd.get_dummies(df_encoded, columns=nominal_cols, drop_first=True)
df_encoded = df_encoded.drop(columns=['assigned_loan_subgrade'
                                    , 'issued_month'
                                    , 'earliest_credit_line_date'
                                    , 'occupation'
                                    , 'purpose'
                                    , 'title'
                                    , 'address'
                                    , 'city'
                                    , 'state'])
print(df_encoded)

In [ ]:
df_encoded.columns

In [ ]:
df['assigned_loan_grade'].value_counts()

In [ ]:
df_encoded['assigned_loan_grade'].value_counts()

In [ ]:
cols_to_keep = [col for col in df_encoded.columns if not (col.startswith('purpose') or col.startswith('zip') or col.startswith('home'))]
df_filtered = df_encoded[cols_to_keep]

In [ ]:
plt.figure(figsize=(18, 10))
sns.heatmap(df_filtered.corr(), annot=True)

In [ ]:
corr = df_filtered.corr()
threshold = 0.25
mask = corr.abs() <= threshold

plt.figure(figsize=(15, 10))
sns.heatmap(corr,
            mask=mask,          # Apply the mask based on your logic
            annot=True,         # Show the numbers
            fmt=".2f",          # Limit to 2 decimal places
            cmap='coolwarm',    # Red for positive, Blue for negative
            center=0,           # Ensure 0 is the neutral color
            linewidths=1,      # Add thin lines between cells for readability
            cbar_kws={"shrink": .8})

plt.title(f"Correlation Heatmap (Only |r| > {threshold:.2f})", fontsize=16)
plt.xticks(ha='right')
plt.show()

### **Splitting the dataset into X and y variables**

In [ ]:
df_scaled = df_encoded.copy()

In [ ]:
X = df_scaled.drop(columns=['loan_status'])
y = df_scaled['loan_status']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

### **Scaling the dataset for further analysis**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled

In [ ]:
from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression(solver='lbfgs', max_iter=1000, class_weight='balanced')
log_model.fit(X_train_scaled, y_train)
predictions = log_model.predict(X_test_scaled)

In [ ]:
# Create a dataframe to view coefficients alongside feature names
coeff_df = pd.DataFrame(log_model.coef_[0], X.columns, columns=['Coefficient'])
print(coeff_df.sort_values(by='Coefficient', ascending=False))

In [ ]:
print(f"Model Intercept: {log_model.intercept_[0]}")

### **Logistic Regression Model Metrics**

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
# 1. Print the Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, predictions))

# 2. Print the Classification Report
print("\nClassification Report:")
print(classification_report(y_test, predictions))

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

# 1. Get the probabilities for the positive class (Charged Off)
# log_model.predict_proba returns [prob_0, prob_1]. We want index 1.
y_probs = log_model.predict_proba(X_test_scaled)[:, 1]

# 2. Calculate the ROC curve points
fpr, tpr, thresholds = roc_curve(y_test, y_probs)

# 3. Calculate the AUC (Area Under the Curve)
auc_score = roc_auc_score(y_test, y_probs)

# 4. Plotting
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', label=f'ROC curve (area = {auc_score:.2f})')
plt.plot([0, 1], [0, 1], color='navy', linestyle='--') # The "Random Guess" line
plt.xlabel('False Positive Rate (1 - Specificity)')
plt.ylabel('True Positive Rate (Sensitivity/Recall)')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

### **Cross validation**

In [ ]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# 1. Define the algorithms to compare
models = {"Logistic Regression": LogisticRegression(max_iter=1000)
        , "Random Forest": RandomForestClassifier(n_estimators=100)
        , "Gradient Boosting": GradientBoostingClassifier()}

# 2. Set up Stratified K-Fold (5 folds is standard)
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

# 3. Iterate and evaluate
results = {}

for name, model in models.items():
    # We use 'roc_auc' as the metric since it's best for credit risk
    cv_scores = cross_val_score(model, X_train_scaled, y_train, cv=skf, scoring='roc_auc')
    results[name] = cv_scores
    print(f"{name} AUC: {np.mean(cv_scores):.4f} (+/- {np.std(cv_scores):.4f})")

In [ ]:
plt.figure(figsize=(10, 6))
plt.boxplot(results.values(), tick_labels=results.keys())
plt.title('Algorithm Comparison (ROC AUC Score)')
plt.ylabel('AUC Score')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# 1. Define the parameter grid
# We test different 'depths' and 'estimators' to find the balance between learning and overfitting
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'bootstrap': [True]
}

# 2. Initialize the Grid Search
# We use 'roc_auc' because catching defaults is our primary goal
grid_search = GridSearchCV(estimator=RandomForestClassifier(random_state=42),
                           param_grid=param_grid,
                           cv=3, # 3-fold CV to keep it fast
                           scoring='roc_auc',
                           n_jobs=-1, # Uses all your CPU cores
                           verbose=2)

# 3. Fit the search to your scaled training data
grid_search.fit(X_train_scaled, y_train)

# 4. Get the best results
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best Cross-Validation AUC: {grid_search.best_score_:.4f}")

In [ ]:
# Use the best model found by Grid Search
final_model = grid_search.best_estimator_

# Check performance on the test set
final_probs = final_model.predict_proba(X_test_scaled)[:, 1]
final_auc = roc_auc_score(y_test, final_probs)

print(f"Final Test Set AUC: {final_auc:.4f}")